In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import OrdinalEncoder
import warnings
warnings.filterwarnings('ignore')


In [125]:
df=pd.read_csv("/content/adult_with_headers.csv")

In [126]:
df.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [127]:
df.shape

(32561, 15)

In [128]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [129]:
# EDA

In [130]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [131]:
df.duplicated().sum()

24

In [132]:
df[df.duplicated(keep='first')]

age          workclass  fnlwgt      education  education_num  \
4881    25            Private  308144      Bachelors             13   
5104    90            Private   52386   Some-college             10   
9171    21            Private  250051   Some-college             10   
11631   20            Private  107658   Some-college             10   
13084   25            Private  195994        1st-4th              2   
15059   21            Private  243368      Preschool              1   
17040   46            Private  173243        HS-grad              9   
18555   30            Private  144593        HS-grad              9   
18698   19            Private   97261        HS-grad              9   
21318   19            Private  138153   Some-college             10   
21490   19            Private  146679   Some-college             10   
21875   49            Private   31267        7th-8th              4   
22300   25            Private  195994        1st-4th              2   
22367   44            Private  367749      Bachelors             13   
22494   49   Self-emp-not-inc   43479   Some-college             10   
25872   23            Private  240137        5th-6th              3   
26313   28            Private  274679        Masters             14   
28230   27            Private  255582        HS-grad              9   
28522   42            Private  204235   Some-college             10   
28846   39            Private   30916        HS-grad              9   
29157   38            Private  207202        HS-grad              9   
30845   46            Private  133616   Some-college             10   
31993   19            Private  251579   Some-college             10   
32404   35            Private  379959        HS-grad              9   

            marital_status          occupation    relationship  \
4881         Never-married        Craft-repair   Not-in-family   
5104         Never-married       Other-service   Not-in-family   
9171         Never-married      Prof-specialty       Own-child   
11631        Never-married        Tech-support   Not-in-family   
13084        Never-married     Priv-house-serv   Not-in-family   
15059        Never-married     Farming-fishing   Not-in-family   
17040   Married-civ-spouse        Craft-repair         Husband   
18555        Never-married       Other-service   Not-in-family   
18698        Never-married     Farming-fishing   Not-in-family   
21318        Never-married        Adm-clerical       Own-child   
21490        Never-married     Exec-managerial       Own-child   
21875   Married-civ-spouse        Craft-repair         Husband   
22300        Never-married     Priv-house-serv   Not-in-family   
22367        Never-married      Prof-specialty   Not-in-family   
22494   Married-civ-spouse        Craft-repair         Husband   
25872        Never-married   Handlers-cleaners   Not-in-family   
26313        Never-married      Prof-specialty   Not-in-family   
28230        Never-married   Machine-op-inspct   Not-in-family   
28522   Married-civ-spouse      Prof-specialty         Husband   
28846   Married-civ-spouse        Craft-repair         Husband   
29157   Married-civ-spouse   Machine-op-inspct         Husband   
30845             Divorced        Adm-clerical       Unmarried   
31993        Never-married       Other-service       Own-child   
32404             Divorced       Other-service   Not-in-family   

                      race      sex  capital_gain  capital_loss  \
4881                 White     Male             0             0   
5104    Asian-Pac-Islander     Male             0             0   
9171                 White   Female             0             0   
11631                White   Female             0             0   
13084                White   Female             0             0   
15059                White     Male             0             0   
17040                White     Male             0             0   
18555                Black     Male         

In [133]:
df.drop_duplicates(inplace=True)

In [134]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [135]:
df

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32537 rows x 15 columns]

In [136]:
df['income'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [137]:
df['workclass'].value_counts()

workclass
 Private             22673
 Self-emp-not-inc     2540
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: count, dtype: int64

In [138]:
names=df.columns
names

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [139]:
df['education'].value_counts()

education
 HS-grad         10494
 Some-college     7282
 Bachelors        5353
 Masters          1722
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           645
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           332
 1st-4th           166
 Preschool          50
Name: count, dtype: int64

In [140]:
oe=OrdinalEncoder()
df=oe.fit_transform(df)

In [141]:
df=pd.DataFrame(df,columns=names)
df

age  workclass   fnlwgt  education  education_num  marital_status  \
0      22.0        7.0   2671.0        9.0           12.0             4.0   
1      33.0        6.0   2926.0        9.0           12.0             2.0   
2      21.0        4.0  14086.0       11.0            8.0             0.0   
3      36.0        4.0  15336.0        1.0            6.0             2.0   
4      11.0        4.0  19355.0        9.0           12.0             2.0   
...     ...        ...      ...        ...            ...             ...   
32532  10.0        4.0  16528.0        7.0           11.0             2.0   
32533  23.0        4.0   8080.0       11.0            8.0             2.0   
32534  41.0        4.0   7883.0       11.0            8.0             6.0   
32535   5.0        4.0  12881.0       11.0            8.0             4.0   
32536  35.0        5.0  17825.0       11.0            8.0             2.0   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0             1.0           1.0   4.0  1.0          25.0           0.0   
1             4.0           0.0   4.0  1.0           0.0           0.0   
2             6.0           1.0   4.0  1.0           0.0           0.0   
3             6.0           0.0   2.0  1.0           0.0           0.0   
4            10.0           5.0   2.0  0.0           0.0           0.0   
...           ...           ...   ...  ...           ...           ...   
32532        13.0           5.0   4.0  0.0           0.0           0.0   
32533         7.0           0.0   4.0  1.0           0.0           0.0   
32534         1.0           4.0   4.0  0.0           0.0           0.0   
32535         1.0           3.0   4.0  1.0           0.0           0.0   
32536         4.0           5.0   4.0  0.0         108.0           0.0   

       hours_per_week  native_country  income  
0                39.0            39.0     0.0  
1                12.0            39.0     0.0  
2                39.0            39.0     0.0  
3                39.0            39.0     0.0  
4                39.0             5.0     0.0  
...               ...             ...     ...  
32532            37.0            39.0     0.0  
32533            39.0            39.0     1.0  
32534            39.0            39.0     0.0  
32535            19.0            39.0     0.0  
32536            39.0            39.0     1.0  

[32537 rows x 15 columns]

In [142]:
x=df.iloc[:,:-1]
x

age  workclass   fnlwgt  education  education_num  marital_status  \
0      22.0        7.0   2671.0        9.0           12.0             4.0   
1      33.0        6.0   2926.0        9.0           12.0             2.0   
2      21.0        4.0  14086.0       11.0            8.0             0.0   
3      36.0        4.0  15336.0        1.0            6.0             2.0   
4      11.0        4.0  19355.0        9.0           12.0             2.0   
...     ...        ...      ...        ...            ...             ...   
32532  10.0        4.0  16528.0        7.0           11.0             2.0   
32533  23.0        4.0   8080.0       11.0            8.0             2.0   
32534  41.0        4.0   7883.0       11.0            8.0             6.0   
32535   5.0        4.0  12881.0       11.0            8.0             4.0   
32536  35.0        5.0  17825.0       11.0            8.0             2.0   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0             1.0           1.0   4.0  1.0          25.0           0.0   
1             4.0           0.0   4.0  1.0           0.0           0.0   
2             6.0           1.0   4.0  1.0           0.0           0.0   
3             6.0           0.0   2.0  1.0           0.0           0.0   
4            10.0           5.0   2.0  0.0           0.0           0.0   
...           ...           ...   ...  ...           ...           ...   
32532        13.0           5.0   4.0  0.0           0.0           0.0   
32533         7.0           0.0   4.0  1.0           0.0           0.0   
32534         1.0           4.0   4.0  0.0           0.0           0.0   
32535         1.0           3.0   4.0  1.0           0.0           0.0   
32536         4.0           5.0   4.0  0.0         108.0           0.0   

       hours_per_week  native_country  
0                39.0            39.0  
1                12.0            39.0  
2                39.0            39.0  
3                39.0            39.0  
4                39.0             5.0  
...               ...             ...  
32532            37.0            39.0  
32533            39.0            39.0  
32534            39.0            39.0  
32535            19.0            39.0  
32536            39.0            39.0  

[32537 rows x 14 columns]

In [143]:
y=df['income']
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
32532    0.0
32533    1.0
32534    0.0
32535    0.0
32536    1.0
Name: income, Length: 32537, dtype: float64

In [144]:
# Scaling down data using MINMAX Scaler

In [145]:
name2=x.columns
name2

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country'],
      dtype='object')

In [146]:
nm=MinMaxScaler()
x_norm=nm.fit_transform(x)

In [147]:
x_norm=pd.DataFrame(x_norm,columns=name2)
x_norm

age  workclass    fnlwgt  education  education_num  \
0      0.305556      0.875  0.123389   0.600000       0.800000   
1      0.458333      0.750  0.135169   0.600000       0.800000   
2      0.291667      0.500  0.650714   0.733333       0.533333   
3      0.500000      0.500  0.708458   0.066667       0.400000   
4      0.152778      0.500  0.894119   0.600000       0.800000   
...         ...        ...       ...        ...            ...   
32532  0.138889      0.500  0.763524   0.466667       0.733333   
32533  0.319444      0.500  0.373262   0.733333       0.533333   
32534  0.569444      0.500  0.364161   0.733333       0.533333   
32535  0.069444      0.500  0.595048   0.733333       0.533333   
32536  0.486111      0.625  0.823440   0.733333       0.533333   

       marital_status  occupation  relationship  race  sex  capital_gain  \
0            0.666667    0.071429           0.2   1.0  1.0      0.211864   
1            0.333333    0.285714           0.0   1.0  1.0      0.000000   
2            0.000000    0.428571           0.2   1.0  1.0      0.000000   
3            0.333333    0.428571           0.0   0.5  1.0      0.000000   
4            0.333333    0.714286           1.0   0.5  0.0      0.000000   
...               ...         ...           ...   ...  ...           ...   
32532        0.333333    0.928571           1.0   1.0  0.0      0.000000   
32533        0.333333    0.500000           0.0   1.0  1.0      0.000000   
32534        1.000000    0.071429           0.8   1.0  0.0      0.000000   
32535        0.666667    0.071429           0.6   1.0  1.0      0.000000   
32536        0.333333    0.285714           1.0   1.0  0.0      0.915254   

       capital_loss  hours_per_week  native_country  
0               0.0        0.419355        0.951220  
1               0.0        0.129032        0.951220  
2               0.0        0.419355        0.951220  
3               0.0        0.419355        0.951220  
4               0.0        0.419355        0.121951  
...             ...             ...             ...  
32532           0.0        0.397849        0.951220  
32533           0.0        0.419355        0.951220  
32534           0.0        0.419355        0.951220  
32535           0.0        0.204301        0.951220  
32536           0.0        0.419355        0.951220  

[32537 rows x 14 columns]

In [ ]:
# PCA

In [148]:
from sklearn.decomposition import PCA

In [149]:
pca=PCA()
pca.fit_transform(x)

array([[-7.82771683e+03,  1.81025889e+01, -3.58379565e+00, ...,
         3.89208547e+00, -1.67640067e-01,  2.79403595e-01],
       [-7.57271729e+03, -7.39392900e+00,  3.76657485e+00, ...,
         1.96924897e+00, -6.95603028e-02,  2.17295382e-01],
       [ 3.58728360e+03, -6.33206483e+00,  5.57314053e-01, ...,
        -1.20882823e+00, -1.73792666e-01,  2.14037034e-01],
       ...,
       [-2.61571977e+03, -4.47087047e+00,  1.82391758e+01, ...,
         2.54652125e+00, -6.27055518e-01, -1.15390421e-01],
       [ 2.38228724e+03, -9.67630314e+00, -1.97454255e+01, ...,
         1.06069064e+00, -3.97517337e-01,  6.25341914e-01],
       [ 7.32627916e+03,  1.02289288e+02,  1.41399960e+00, ...,
         9.73478827e-01, -5.01968492e-01, -8.80245788e-02]])

In [150]:
var=pca.explained_variance_ratio_

In [151]:
var2=np.cumsum(np.round(var,decimals=4)*100)
var2

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100.])

In [ ]:
# chi2 test

In [152]:
test=SelectKBest(score_func=chi2,k=5)
fit=test.fit(x,y)
set_printoptions(precision=4)
print(fit.scores_)

[1.5358e+04 4.7618e+01 1.2753e+04 2.9810e+02 2.6632e+03 1.1217e+03
 5.0368e+02 3.6582e+03 3.3012e+01 5.0197e+02 3.1410e+05 4.2313e+04
 6.5781e+03 1.3219e+01]


In [153]:
data=pd.DataFrame(fit.scores_).T

In [154]:
data

0         1             2           3            4            5   \
0  15358.124939  47.61835  12752.508363  298.098144  2663.194102  1121.721831   

           6           7          8           9              10           11  \
0  503.675736  3658.21506  33.012176  501.968535  314104.438394  42313.01392   

            12        13  
0  6578.053417  13.21903

In [156]:
data.sort_values(by=0,axis=1,ascending=False)

10           11            0             2            12  \
0  314104.438394  42313.01392  15358.124939  12752.508363  6578.053417   

           7            4            5           6           9           3   \
0  3658.21506  2663.194102  1121.721831  503.675736  501.968535  298.098144   

         1          8         13  
0  47.61835  33.012176  13.21903

In [158]:
# RFE

In [157]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [159]:
model=LogisticRegression()
rfe=RFE(model)
fit=rfe.fit(x,y)

In [160]:
fit.n_features_

7

In [161]:
fit.support_

array([ True, False, False, False,  True,  True, False,  True,  True,
        True, False, False,  True, False])

In [162]:
fit.ranking_

array([1, 3, 8, 5, 1, 1, 6, 1, 1, 1, 4, 2, 1, 7])

In [163]:
x.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country'],
      dtype='object')

In [ ]:
# Decision Tree

In [164]:
from sklearn.tree import DecisionTreeClassifier

In [165]:
model=DecisionTreeClassifier()
model.fit(x,y)


DecisionTreeClassifier()

In [166]:
fe=model.feature_importances_
fe

array([0.1153, 0.0367, 0.2047, 0.0119, 0.1164, 0.0073, 0.0549, 0.1985,
       0.0121, 0.0031, 0.1158, 0.0372, 0.0715, 0.0145])

In [170]:
fe.sort()

In [171]:
fe

array([0.0031, 0.0073, 0.0119, 0.0121, 0.0145, 0.0367, 0.0372, 0.0549,
       0.0715, 0.1153, 0.1158, 0.1164, 0.1985, 0.2047])

In [ ]:
# Random forest

In [172]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier

In [174]:
model=RandomForestClassifier(n_estimators=100,max_features=5)
kfold=KFold(n_splits=10)

In [175]:
result=cross_val_score(model,x,y,cv=kfold)

In [177]:
result

array([0.8451, 0.8611, 0.8583, 0.8546, 0.8556, 0.8568, 0.8593, 0.8632,
       0.8623, 0.8567])

In [178]:
result.mean()

0.8573012363794114